<?php

namespace app\controllers;

use app\models\Article;
use app\models\Category;
use app\models\Like;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

class CategoryController extends Controller
{
    public function beforeAction($action)
    {
        $this->openSession();
        if (!isset($_SESSION['article']['likes'])) {
            foreach (Like::find()->asArray()->all() as $like) {
                $_SESSION[$like['object_type']]['likes'][$like['object_id']][] = $like['user_id'];
            }
        }
        if (!isset($_SESSION['article']['views'])) {
            $_SESSION['article']['views'] = [];
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionView($alias)
    {
        $category = Category::find()->where(['alias' => $alias])->limit(1)->one();
        $this->view->title = $category->title;
        $query = Article::find()->where(['category_id' => $category->id, 'status' => Article::STATUS_PUBLISHED]);
        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'pageSize' => 1,
            'pageSizeParam' => false
        ]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('view', [
            'models' => $models,
            'pages' => $pages,
        ]);
    }

    private function openSession()
    {
        $session = Yii::$app->session;
        if (!$session->isActive) {
            $session->open();
        }
    }
}